plugins {
    id 'com.android.application'
}

android {
    namespace 'com.xoureldeen.vectrasbox'
    compileSdk 35
    ndkVersion '26.1.10909125'

    defaultConfig {
        applicationId 'com.xoureldeen.vectrasbox'
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName '1.0.0 alpha'

        ndk {
            abiFilters 'arm64-v8a'
        }

        externalNativeBuild {
            cmake {
                arguments '-DANDROID_STL=c++_shared'
                cppFlags '-std=c++17'
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    externalNativeBuild {
        cmake {
            path file('src/main/cpp/CMakeLists.txt')
            version '3.22.1'
        }
    }
}

dependencies {
    implementation 'com.google.android.material:material:1.14.0'
    implementation 'androidx.drawerlayout:drawerlayout:1.2.0'
    testImplementation 'junit:junit:4.13.2'
}
